/** ISO alpha-3 → map label (Natural Earth countries with CONTINENT Africa). */
export const AFRICA_COUNTRY_ISO_A3_TO_NAME: Record<string, string> = {
  AGO: "Angola",
  BDI: "Burundi",
  BEN: "Benin",
  BFA: "Burkina Faso",
  BWA: "Botswana",
  CAF: "Central African Republic",
  CIV: "Ivory Coast",
  CMR: "Cameroon",
  COD: "Democratic Republic of the Congo",
  COG: "Republic of the Congo",
  COM: "Comoros",
  CPV: "Cabo Verde",
  DJI: "Djibouti",
  DZA: "Algeria",
  EGY: "Egypt",
  ERI: "Eritrea",
  ESH: "Western Sahara",
  ETH: "Ethiopia",
  GAB: "Gabon",
  GHA: "Ghana",
  GIN: "Guinea",
  GMB: "Gambia",
  GNB: "Guinea-Bissau",
  GNQ: "Equatorial Guinea",
  KEN: "Kenya",
  LBR: "Liberia",
  LBY: "Libya",
  LSO: "Lesotho",
  MAR: "Morocco",
  MDG: "Madagascar",
  MLI: "Mali",
  MOZ: "Mozambique",
  MRT: "Mauritania",
  MWI: "Malawi",
  NAM: "Namibia",
  NER: "Niger",
  NGA: "Nigeria",
  RWA: "Rwanda",
  SDN: "Sudan",
  SEN: "Senegal",
  SLE: "Sierra Leone",
  SOL: "Somaliland",
  SOM: "Somalia",
  SSD: "South Sudan",
  STP: "São Tomé and Principe",
  SWZ: "eSwatini",
  TCD: "Chad",
  TGO: "Togo",
  TUN: "Tunisia",
  TZA: "United Republic of Tanzania",
  UGA: "Uganda",
  ZAF: "South Africa",
  ZMB: "Zambia",
  ZWE: "Zimbabwe",
};
