/** ISO alpha-3 → map label (Natural Earth Asia; excludes Turkey, Georgia, Armenia, Azerbaijan, Cyprus on Europe layer). */
export const ASIA_COUNTRY_ISO_A3_TO_NAME: Record<string, string> = {
  AFG: "Afghanistan",
  ARE: "United Arab Emirates",
  BGD: "Bangladesh",
  BHR: "Bahrain",
  BRN: "Brunei",
  BTN: "Bhutan",
  CHN: "China",
  CYN: "Northern Cyprus",
  HKG: "Hong Kong S.A.R.",
  IDN: "Indonesia",
  IND: "India",
  IRN: "Iran",
  IRQ: "Iraq",
  ISR: "Israel",
  JOR: "Jordan",
  JPN: "Japan",
  KAZ: "Kazakhstan",
  KGZ: "Kyrgyzstan",
  KHM: "Cambodia",
  KOR: "South Korea",
  KWT: "Kuwait",
  LAO: "Laos",
  LBN: "Lebanon",
  LKA: "Sri Lanka",
  MAC: "Macao S.A.R",
  MMR: "Myanmar",
  MNG: "Mongolia",
  MYS: "Malaysia",
  NPL: "Nepal",
  OMN: "Oman",
  PAK: "Pakistan",
  PHL: "Philippines",
  PRK: "North Korea",
  PSE: "Palestine",
  QAT: "Qatar",
  SAU: "Saudi Arabia",
  SGP: "Singapore",
  SYR: "Syria",
  THA: "Thailand",
  TJK: "Tajikistan",
  TKM: "Turkmenistan",
  TLS: "East Timor",
  TWN: "Taiwan",
  UZB: "Uzbekistan",
  VNM: "Vietnam",
  YEM: "Yemen",
};
