/** ISO alpha-3 → map label (Natural Earth SUBREGION Caribbean; Puerto Rico & USVI omitted — US atlas). */
export const CARIBBEAN_COUNTRY_ISO_A3_TO_NAME: Record<string, string> = {
  ABW: "Aruba",
  AIA: "Anguilla",
  ATG: "Antigua and Barbuda",
  BHS: "The Bahamas",
  BLM: "Saint Barthelemy",
  BRB: "Barbados",
  CUB: "Cuba",
  CUW: "Curaçao",
  CYM: "Cayman Islands",
  DMA: "Dominica",
  DOM: "Dominican Republic",
  GRD: "Grenada",
  HTI: "Haiti",
  JAM: "Jamaica",
  KNA: "Saint Kitts and Nevis",
  LCA: "Saint Lucia",
  MAF: "Saint Martin",
  MSR: "Montserrat",
  SXM: "Sint Maarten",
  TCA: "Turks and Caicos Islands",
  TTO: "Trinidad and Tobago",
  VCT: "Saint Vincent and the Grenadines",
  VGB: "British Virgin Islands",
};
