/** ISO 3166-1 alpha-3 (Natural Earth `ISO_A3` / `ADM0_A3`) → map label. Georgia uses `Georgia (Europe)` vs US state Georgia. */
export const EUROPE_COUNTRY_ISO_A3_TO_NAME: Record<string, string> = {
  ALA: "Aland",
  ALB: "Albania",
  AND: "Andorra",
  ARM: "Armenia",
  AUT: "Austria",
  AZE: "Azerbaijan",
  BEL: "Belgium",
  BGR: "Bulgaria",
  BIH: "Bosnia and Herzegovina",
  BLR: "Belarus",
  CHE: "Switzerland",
  CYP: "Cyprus",
  CZE: "Czechia",
  DEU: "Germany",
  DNK: "Denmark",
  ESP: "Spain",
  EST: "Estonia",
  FIN: "Finland",
  FRA: "France",
  FRO: "Faroe Islands",
  GEO: "Georgia (Europe)",
  GGY: "Guernsey",
  GRC: "Greece",
  GBR: "United Kingdom",
  HRV: "Croatia",
  HUN: "Hungary",
  IMN: "Isle of Man",
  ISL: "Iceland",
  IRL: "Ireland",
  ITA: "Italy",
  JEY: "Jersey",
  KOS: "Kosovo",
  LIE: "Liechtenstein",
  LTU: "Lithuania",
  LUX: "Luxembourg",
  LVA: "Latvia",
  MCO: "Monaco",
  MDA: "Moldova",
  MKD: "North Macedonia",
  MLT: "Malta",
  MNE: "Montenegro",
  NLD: "Netherlands",
  NOR: "Norway",
  POL: "Poland",
  PRT: "Portugal",
  ROU: "Romania",
  RUS: "Russia",
  SMR: "San Marino",
  SRB: "Republic of Serbia",
  SVK: "Slovakia",
  SVN: "Slovenia",
  SWE: "Sweden",
  TUR: "Turkey",
  UKR: "Ukraine",
  VAT: "Vatican",
};
