/** ISO alpha-3 → map label (Natural Earth Oceania; Guam, American Samoa, N. Mariana omitted — US atlas). */
export const OCEANIA_COUNTRY_ISO_A3_TO_NAME: Record<string, string> = {
  ATC: "Ashmore and Cartier Islands",
  AUS: "Australia",
  COK: "Cook Islands",
  FJI: "Fiji",
  FSM: "Federated States of Micronesia",
  KIR: "Kiribati",
  MHL: "Marshall Islands",
  NCL: "New Caledonia",
  NFK: "Norfolk Island",
  NIU: "Niue",
  NRU: "Nauru",
  NZL: "New Zealand",
  PCN: "Pitcairn Islands",
  PLW: "Palau",
  PNG: "Papua New Guinea",
  PYF: "French Polynesia",
  SLB: "Solomon Islands",
  TON: "Tonga",
  TUV: "Tuvalu",
  VUT: "Vanuatu",
  WLF: "Wallis and Futuna",
  WSM: "Samoa",
};
